### PR TITLE
v0.47.2

### PR DESCRIPTION
**Pull request by zolanaj**
https://github.com/NREL/REopt.jl/pull/401
https://github.com/NREL/REopt.jl/pull/415

### CODE REVIEW

**Review by adfarth — APPROVED** [review]
@zolanaj Approving pending the macOS tests passing! Just to double check, are any changes in the API required other than updating the REopt version #?

**Comment by Bill-Becker** [comment]
@adfarth @zolanaj Since the windows test passed, we can ignore waiting for Mac. Alex - I'd really like to get another PR in there for an IEDO-requested fix: https://github.com/NREL/REopt.jl/pull/415, if you don't mind reviewing that quickly.

**Comment by zolanaj** [comment]
> @adfarth @zolanaj Since the windows test passed, we can ignore waiting for Mac. Alex - I'd really like to get another PR in there for an IEDO-requested fix: #415, if you don't mind reviewing that quickly.

@Bill-Becker review completed, and after the minor comment is addressed I can merge and register the new version.

**Comment by Bill-Becker** [comment]
> > @adfarth @zolanaj Since the windows test passed, we can ignore waiting for Mac. Alex - I'd really like to get another PR in there for an IEDO-requested fix: #415, if you don't mind reviewing that quickly.
> 
> @Bill-Becker review completed, and after the minor comment is addressed I can merge and register the new version.

@zolanaj thanks for the quick review - let me know if my response on that PR addresses your comment.

**Comment by Bill-Becker** [comment]
@zolanaj thanks for merging the other PR, and for adding the CHANGELOG line. I approve this PR as well!

**Pull request merged**
