### PR TITLE
Updated Process Heat load structure

### PR DESCRIPTION
**Pull request by bpulluta**
This PR updates the existing process heat load structure to accept default industrial heat load configurations

### CODE REVIEW

**Comment by bpulluta** [comment]
> @bpulluta Looks good! I made some updates, most notably I made a new simulated_load function for separately getting space heating, DHW, and process heat (added those load types) while _preserving_ (reverting to) the existing response of the load type `heating_load` which just gives the space heating and DHW data. I did this because of how we plan to add these new loads to the web tool. I also fixed some tests, and now all tests are passing.

Awesome! Thanks for your help @Bill-Becker. I was just about to message you to schedule some time for debugging the tests. Happy to see everything is working now.

**Comment by bpulluta** [comment]
@Bill-Becker One question. Here: https://github.com/NREL/REopt.jl/blob/7c522f4ae45c160bfeb4b412c82009dbedfe06fc/test/runtests.jl#L2045

Should I add `ProcessHeatLoad` to the test within the `re_emissions_with_thermal.json`?

If that is not necessary, I can go ahead an merge

**Review by Bill-Becker — APPROVED** [review]
Thanks!

**Comment by bpulluta** [comment]
> Thanks!

Before I merge just want to check with you about the question above (or below copied here):

@Bill-Becker One question. Here: https://github.com/NREL/REopt.jl/blob/7c522f4ae45c160bfeb4b412c82009dbedfe06fc/test/runtests.jl#L2045

Should I add `ProcessHeatLoad` to the test within the `re_emissions_with_thermal.json`?

If that is not necessary, I can go ahead an merge

**Comment by Bill-Becker** [comment]
> `ProcessHeatLoad`

Not necessary to add anything else.

**Pull request merged**
