### PR TITLE
Migrate tests from Xpress to HiGHS

### PR DESCRIPTION
**Pull request by zolanaj**
This PR migrates the test suite formerly using Xpress in `test/test_with_xpress.jl` to `test/runtests.jl`.  Many of the tests that are incompatible with HiGHS due to the presence of indicator constraints have been commented out (using `@test_skip` leads to errors as testsets often parse results of one REopt run before populating another), and a test checking for incompatibility or infeasibility has taken their place where appropriate.

### CODE REVIEW

**Comment by zolanaj** [comment]
@Bill-Becker I am waiting for a queued check (mac-PR) in the workflow to complete before I can restart the canceled one (windows-push), but the changes are ready for your review (the full test suite in ubuntu is passing).

**Comment by Bill-Becker** [comment]
@zolanaj Could you make a .txt file in the test folder and make a list of the testsets (not each test) which were skipped and why? Also list testsets which were not skipped but the expected results changed (significantly enough to want to figure out why at some point later).

**Comment by zolanaj** [comment]
> @zolanaj Could you make a .txt file in the test folder and make a list of the testsets (not each test) which were skipped and why? Also list testsets which were not skipped but the expected results changed (significantly enough to want to figure out why at some point later).

I added this in commit https://github.com/NREL/REopt.jl/commit/1dbf4ceca89097782cbb3533a7bc3284b5eda3ee

Some of the root causes have a couple options because I haven't fully dug into them.

**Review by Bill-Becker — APPROVED** [review]
Thanks Alex! PR https://github.com/NREL/REopt.jl/pull/341 is ready to accept this merge.

**Pull request merged**
