### PR TITLE
v. 0.46.0

### PR DESCRIPTION
**Pull request by zolanaj**
https://github.com/NREL/REopt.jl/pull/383
https://github.com/NREL/REopt.jl/pull/378
https://github.com/NREL/REopt.jl/pull/373
https://github.com/NREL/REopt.jl/pull/356
https://github.com/NREL/REopt.jl/pull/379
https://github.com/NREL/REopt.jl/pull/389
https://github.com/NREL/REopt.jl/pull/390
https://github.com/NREL/REopt.jl/pull/376

### CODE REVIEW

**Comment by adfarth** [comment]
@zolanaj  this description should include #356, correct? For #356, I'm wondering if there are plans to update the REopt API with the new inputs (and outputs, if any) as well as updates to the user manual?

**Comment by zolanaj** [comment]
> @zolanaj this description should include #356, correct? For #356, I'm wondering if there are plans to update the REopt API with the new inputs (and outputs, if any) as well as updates to the user manual?

Yes and yes! My intent is to move to API development and incorporate all the new inputs and outputs; this, along with the addition of ASHP into REopt.jl and the API, is my priority for development this month.  However there is no API PR ready yet.

**Review by adfarth — APPROVED** [review]
@zolanaj approving with the caveat that we still need to double check compatibility with the API! 
In addition: do the thermal updates included here require any changes to the User Manual or Web Tool inputs or tooltips?

**Comment by zolanaj** [comment]
> @zolanaj approving with the caveat that we still need to double check compatibility with the API! In addition: do the thermal updates included here require any changes to the User Manual or Web Tool inputs or tooltips?

To get all the results in and working on the Julia side I have this open: https://github.com/NREL/REopt.jl/pull/389

The ongoing PR to merge the changes on the API side is in progress here: https://github.com/NREL/REopt_API/pull/583

**Pull request merged**
